spring:
    datasource:
        url: jdbc:mysql://rm-uf6g41we475x26qtto.mysql.rds.aliyuncs.com:3306/xijing?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
        username: root
        password: 3828399@lifan
        driver-class-name: com.mysql.jdbc.Driver
    redis:
      host: 127.0.0.1
      port: 6379