spring:
    datasource:
        url: jdbc:mysql://www.xijinghuiyan.com:3306/xijing?useUnicode=true&characterEncoding=utf8
        username: root
        password: 3828399.lifan
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#    jpa:
#      hibernate:
#        ddl-auto: update
    redis:
      host: 127.0.0.1
      port: 6379
      password: root
    activemq:
      broker-url: tcp://xijinghuiyan.com:61616
      in-memory: true
      pool:
        enabled: false
      user: admin
      password: admin

server:
    port: 80